//
// auto-generated by op2.py
//

// global constants
extern double gam;
extern double gm1;
extern double gm1i;
extern double m2;
extern double wtg1[2];
extern double xi1[2];
extern double Ng1[4];
extern double Ng1_xi[4];
extern double wtg2[4];
extern double Ng2[16];
extern double Ng2_xi[32];
extern double minf;
extern double freq;
extern double kappa;
extern double nmode;
extern double mfan;

// header
#include "op_lib_c.h"


void op_decl_const_gam(int dim, char const *type,
                       double *dat){
}

void op_decl_const_gm1(int dim, char const *type,
                       double *dat){
}

void op_decl_const_gm1i(int dim, char const *type,
                       double *dat){
}

void op_decl_const_m2(int dim, char const *type,
                       double *dat){
}

void op_decl_const_wtg1(int dim, char const *type,
                       double *dat){
}

void op_decl_const_xi1(int dim, char const *type,
                       double *dat){
}

void op_decl_const_Ng1(int dim, char const *type,
                       double *dat){
}

void op_decl_const_Ng1_xi(int dim, char const *type,
                       double *dat){
}

void op_decl_const_wtg2(int dim, char const *type,
                       double *dat){
}

void op_decl_const_Ng2(int dim, char const *type,
                       double *dat){
}

void op_decl_const_Ng2_xi(int dim, char const *type,
                       double *dat){
}

void op_decl_const_minf(int dim, char const *type,
                       double *dat){
}

void op_decl_const_freq(int dim, char const *type,
                       double *dat){
}

void op_decl_const_kappa(int dim, char const *type,
                       double *dat){
}

void op_decl_const_nmode(int dim, char const *type,
                       double *dat){
}

void op_decl_const_mfan(int dim, char const *type,
                       double *dat){
}

// user kernel files
#include "res_calc_acckernel.c"
#include "dirichlet_acckernel.c"
#include "init_cg_acckernel.c"
#include "spMV_acckernel.c"
#include "dotPV_acckernel.c"
#include "updateUR_acckernel.c"
#include "dotR_acckernel.c"
#include "updateP_acckernel.c"
#include "update_acckernel.c"
