//
// auto-generated by op2.py
//

// global constants
float alpha_ompkernel;

// header
#include "op_lib_cpp.h"


void op_decl_const_alpha(int dim, char const *type,
                       float *dat){
  memcpy(&alpha_ompkernel, dat, dim*sizeof(float));
  #pragma omp target enter data map(to:alpha_ompkernel)
}

// user kernel files
#include "res_omp4kernel_func.cpp"
#include "update_omp4kernel_func.cpp"
