//
// auto-generated by op2.py
//

// global constants
double alpha_ompkernel;

// header
#include "../user_types.h"
#include "op_lib_cpp.h"


void op_decl_const_alpha(int dim, char const *type,
                       double *dat){
  memcpy(&alpha_ompkernel, dat, dim*sizeof(double));
  #pragma omp target enter data map(to:alpha_ompkernel)
}

// user kernel files
#include "res_omp4kernel_func.cpp"
#include "update_omp4kernel_func.cpp"
