//
// auto-generated by op2.py
//

#ifdef _OPENMP
  #include <omp.h>
#endif

// global constants
extern double gam;
extern double gm1;
extern double cfl;
extern double eps;
extern double mach;
extern double alpha;
extern double qinf[4];

// header
#include "op_lib_cpp.h"

#ifndef SKIP_DECL_CONST

void op_decl_const_gam(int dim, char const *type,
                       double *dat){
}

void op_decl_const_gm1(int dim, char const *type,
                       double *dat){
}

void op_decl_const_cfl(int dim, char const *type,
                       double *dat){
}

void op_decl_const_eps(int dim, char const *type,
                       double *dat){
}

void op_decl_const_mach(int dim, char const *type,
                       double *dat){
}

void op_decl_const_alpha(int dim, char const *type,
                       double *dat){
}

void op_decl_const_qinf(int dim, char const *type,
                       double *dat){
}
#endif

// user kernel files
#include "save_soln_kernel.cpp"
#include "adt_calc_kernel.cpp"
#include "res_calc_kernel.cpp"
#include "bres_calc_kernel.cpp"
#include "update_kernel.cpp"
