//
// auto-generated by op2.py
//

#ifdef _OPENMP
  #include <omp.h>
#endif

// global constants
extern double alpha;

// header
#include "../user_types.h"
#include "op_lib_cpp.h"

#ifndef SKIP_DECL_CONST

void op_decl_const_alpha(int dim, char const *type,
                       double *dat){
}
#endif

// user kernel files
#include "res_kernel.cpp"
#include "update_kernel.cpp"
