//
// auto-generated by op2.py
//

//global constants
#ifndef MAX_CONST_SIZE
#define MAX_CONST_SIZE 128
#endif

__constant__ float alpha_cuda;

//header
#include "op_lib_cpp.h"
#include "op_cuda_rt_support.h"
#include "op_cuda_reduction.h"

void op_decl_const_alpha(int dim, char const *type,
                       float *dat){
  if (!OP_hybrid_gpu) return;
  cutilSafeCall(cudaMemcpyToSymbol(alpha_cuda, dat, dim*sizeof(float)));
}

//user kernel files
#include "res_kernel.cu"
#include "update_kernel.cu"
