//
// auto-generated by op2.py
//

//global constants
#ifndef MAX_CONST_SIZE
#define MAX_CONST_SIZE 128
#endif

__constant__ double gam_cuda;
__constant__ double gm1_cuda;
__constant__ double gm1i_cuda;
__constant__ double m2_cuda;
__constant__ double wtg1_cuda[2];
__constant__ double xi1_cuda[2];
__constant__ double Ng1_cuda[4];
__constant__ double Ng1_xi_cuda[4];
__constant__ double wtg2_cuda[4];
__constant__ double Ng2_cuda[16];
__constant__ double Ng2_xi_cuda[32];
__constant__ double minf_cuda;
__constant__ double freq_cuda;
__constant__ double kappa_cuda;
__constant__ double nmode_cuda;
__constant__ double mfan_cuda;

//header
#include "op_lib_cpp.h"
#include "op_cuda_rt_support.h"
#include "op_cuda_reduction.h"

void op_decl_const_gam(int dim, char const *type,
                       double *dat){
  if (!OP_hybrid_gpu) return;
  cutilSafeCall(cudaMemcpyToSymbol(gam_cuda, dat, dim*sizeof(double)));
}

void op_decl_const_gm1(int dim, char const *type,
                       double *dat){
  if (!OP_hybrid_gpu) return;
  cutilSafeCall(cudaMemcpyToSymbol(gm1_cuda, dat, dim*sizeof(double)));
}

void op_decl_const_gm1i(int dim, char const *type,
                       double *dat){
  if (!OP_hybrid_gpu) return;
  cutilSafeCall(cudaMemcpyToSymbol(gm1i_cuda, dat, dim*sizeof(double)));
}

void op_decl_const_m2(int dim, char const *type,
                       double *dat){
  if (!OP_hybrid_gpu) return;
  cutilSafeCall(cudaMemcpyToSymbol(m2_cuda, dat, dim*sizeof(double)));
}

void op_decl_const_wtg1(int dim, char const *type,
                       double *dat){
  if (!OP_hybrid_gpu) return;
  if (dim*sizeof(double)>MAX_CONST_SIZE) {
    printf("error: MAX_CONST_SIZE not big enough\n"); exit(1);
  }
  cutilSafeCall(cudaMemcpyToSymbol(wtg1_cuda, dat, dim*sizeof(double)));
}

void op_decl_const_xi1(int dim, char const *type,
                       double *dat){
  if (!OP_hybrid_gpu) return;
  if (dim*sizeof(double)>MAX_CONST_SIZE) {
    printf("error: MAX_CONST_SIZE not big enough\n"); exit(1);
  }
  cutilSafeCall(cudaMemcpyToSymbol(xi1_cuda, dat, dim*sizeof(double)));
}

void op_decl_const_Ng1(int dim, char const *type,
                       double *dat){
  if (!OP_hybrid_gpu) return;
  if (dim*sizeof(double)>MAX_CONST_SIZE) {
    printf("error: MAX_CONST_SIZE not big enough\n"); exit(1);
  }
  cutilSafeCall(cudaMemcpyToSymbol(Ng1_cuda, dat, dim*sizeof(double)));
}

void op_decl_const_Ng1_xi(int dim, char const *type,
                       double *dat){
  if (!OP_hybrid_gpu) return;
  if (dim*sizeof(double)>MAX_CONST_SIZE) {
    printf("error: MAX_CONST_SIZE not big enough\n"); exit(1);
  }
  cutilSafeCall(cudaMemcpyToSymbol(Ng1_xi_cuda, dat, dim*sizeof(double)));
}

void op_decl_const_wtg2(int dim, char const *type,
                       double *dat){
  if (!OP_hybrid_gpu) return;
  if (dim*sizeof(double)>MAX_CONST_SIZE) {
    printf("error: MAX_CONST_SIZE not big enough\n"); exit(1);
  }
  cutilSafeCall(cudaMemcpyToSymbol(wtg2_cuda, dat, dim*sizeof(double)));
}

void op_decl_const_Ng2(int dim, char const *type,
                       double *dat){
  if (!OP_hybrid_gpu) return;
  if (dim*sizeof(double)>MAX_CONST_SIZE) {
    printf("error: MAX_CONST_SIZE not big enough\n"); exit(1);
  }
  cutilSafeCall(cudaMemcpyToSymbol(Ng2_cuda, dat, dim*sizeof(double)));
}

void op_decl_const_Ng2_xi(int dim, char const *type,
                       double *dat){
  if (!OP_hybrid_gpu) return;
  if (dim*sizeof(double)>MAX_CONST_SIZE) {
    printf("error: MAX_CONST_SIZE not big enough\n"); exit(1);
  }
  cutilSafeCall(cudaMemcpyToSymbol(Ng2_xi_cuda, dat, dim*sizeof(double)));
}

void op_decl_const_minf(int dim, char const *type,
                       double *dat){
  if (!OP_hybrid_gpu) return;
  cutilSafeCall(cudaMemcpyToSymbol(minf_cuda, dat, dim*sizeof(double)));
}

void op_decl_const_freq(int dim, char const *type,
                       double *dat){
  if (!OP_hybrid_gpu) return;
  cutilSafeCall(cudaMemcpyToSymbol(freq_cuda, dat, dim*sizeof(double)));
}

void op_decl_const_kappa(int dim, char const *type,
                       double *dat){
  if (!OP_hybrid_gpu) return;
  cutilSafeCall(cudaMemcpyToSymbol(kappa_cuda, dat, dim*sizeof(double)));
}

void op_decl_const_nmode(int dim, char const *type,
                       double *dat){
  if (!OP_hybrid_gpu) return;
  cutilSafeCall(cudaMemcpyToSymbol(nmode_cuda, dat, dim*sizeof(double)));
}

void op_decl_const_mfan(int dim, char const *type,
                       double *dat){
  if (!OP_hybrid_gpu) return;
  cutilSafeCall(cudaMemcpyToSymbol(mfan_cuda, dat, dim*sizeof(double)));
}

//user kernel files
#include "res_calc_kernel.cu"
#include "dirichlet_kernel.cu"
#include "init_cg_kernel.cu"
#include "spMV_kernel.cu"
#include "dotPV_kernel.cu"
#include "updateUR_kernel.cu"
#include "dotR_kernel.cu"
#include "updateP_kernel.cu"
#include "update_kernel.cu"
